#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Checks if branch has something pending.
function branch_has_pending_actions() {
  git diff --quiet --ignore-submodules HEAD 2>/dev/null; [ $? -eq 1 ] && echo "*"
}

# Gets the current git branch.
function get_current_git_branch() {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(branch_has_pending_actions)/"
}

# Evaluate and define the necessary variables.
CURRENT_GIT_BRANCH=$(get_current_git_branch)
HUSKY_GIT_BRANCHES=("main|dev")
PROTECTED_BRANCH="main"
PROTECTED_FILES=("launch.json|.env|stylecop.json")

# Prevents commiting directly to the protected branch.
if [ "$CURRENT_GIT_BRANCH" = "$PROTECTED_BRANCH" ]; then
  echo "You can't commit directly to a protected branch!"
  exit 1
fi

# Prevents changes to protected files.
if git diff --cached --name-only | grep -qE $PROTECTED_FILES; then
  echo "You tried to change a file which is not allowed to be changed!"
  exit 1;
fi

# Check whether to run the husky command or not. Runs the pre-commit script only if branch matches the defined branches.
if [[ "${IFS}${HUSKY_GIT_BRANCHES[*]}${IFS}" =~ "${IFS}${CURRENT_GIT_BRANCH}${IFS}" ]]; then
  echo "running husky command on ${CURRENT_GIT_BRANCH}..."
  npm run pre-commit
else
  echo "skipping husky command for branch ${CURRENT_GIT_BRANCH}..."
  exit 0;
fi
